### ISSUE TITLE
`lui` imm error.

### ISSUE THREAD

**Issue by caterpillar-1** [dream-tentacle/riscv32-bits-to-code#1]
When disassembling `lui` instructions, the `imm` part seems not correct.
Here are the screenshots:
dut:
![Screenshot from 2023-11-30 20-25-29](https://github.com/dream-tentacle/riscv32-bits-to-code/assets/39209322/c0637aed-40af-4b5e-baf1-fa4468943fef)
ref: [riscv-instruction-disassembler](https://github.com/niladut/riscv-instruction-disassembler)
![Screenshot from 2023-11-30 20-25-45](https://github.com/dream-tentacle/riscv32-bits-to-code/assets/39209322/dea1fbfd-f008-4d27-bc16-0338cad89ec4)
In this case, the imm should be 0xbeef1000.
I'm learning collaboration functions on GitHub, can I fix this bug?

**Comment by dream-tentacle** [comment]
Thank you. It's a small bug and I've fixed that. If you want to fix other bugs later, just make a pull request.
